### ISSUE TITLE
Bidding errors 

### ISSUE THREAD

**Issue by hyoussef** [hunterjm/futgui#107] opened 2016-10-08 09:03 UTC
when start bidding, i see this error in the console 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/i060356/git/personal/futgui/core/bid.py", line 62, in bid
    displayName = asset['Item']['Desc']
KeyError: 'Desc'
```

I think the bids never happens because of that exception.

Using last master branch code line on MacOs Sierra

**Comment by hunterjm** [comment] 2016-10-08 12:28
Duplicate of https://github.com/hunterjm/futgui/issues/25.

Workaround is to clear out your transfer list before running the app.

**Closed as completed by hunterjm** 2016-10-08 12:28 UTC
