### ISSUE TITLE
Application wont open on Mac

### ISSUE THREAD

**Issue by ghost** [hunterjm/futgui#81] opened 2016-10-03 16:01 UTC
I try to open the application, from version 1.0.1. to the newest release 1.1.1. I does just not open in Mac 10.11.6. Application "bounces" a few times, then error report can be generated.

**Comment by ghost** [comment] 2016-10-04 04:30
Do you want me to post or PN you crash report?

**Comment by ghost** [comment] 2016-10-04 18:09
I tried to run from dock bar, but it also does not open

**Comment by ghost** [comment] 2016-10-05 16:20
I loved the app for Fifa 16, would like to use again for Fifa 17.

I tried install it on another Mac, also crashes at startup. Can we work on this error? How can I provide the crash report?

**Comment by hunterjm** [comment] 2016-10-06 17:25
Duplicate of https://github.com/hunterjm/futgui/issues/67.  See there for temporary work around running from source.

**Closed as completed by hunterjm** 2016-10-06 17:25 UTC
