### ISSUE TITLE
Quit unxpectedly - MAC

### ISSUE THREAD

**Issue by fi8471** [hunterjm/futgui#98] opened 2016-10-06 16:15 UTC
mac version quits unexpectedly every time i try to use it. I manage to log in but get no further.

**Comment by JKetelaar** [comment] 2016-10-06 16:28
Same here.
Error-log: https://gist.github.com/JKetelaar/30224463d3e039a5d523bec2c1156e9c

**Comment by hunterjm** [comment] 2016-10-06 17:24
Duplicate of https://github.com/hunterjm/futgui/issues/67.  See there for temporary work/around by running from source code.

**Closed as completed by hunterjm** 2016-10-06 17:24 UTC
