### ISSUE TITLE
Error and Doubt

### ISSUE THREAD

**Issue by OthonGBR** [hunterjm/futgui#30] opened 2015-12-09 13:16 UTC
Is giving this error all the time is only in "Starting Build" program is locked.
![error](https://cloud.githubusercontent.com/assets/14895784/11686184/012f1452-9e66-11e5-814d-3084f4118cad.png)

Doubt: How can I Sniping players? I am new to AutoBuyer and do not understand much.

Thanks :)

**Comment by aftershock9** [comment] 2015-12-10 10:17
Regarding the Sniping functionality - If you check the BIN Snipe box, this will only snipe players:

![image](https://cloud.githubusercontent.com/assets/6708705/11712790/f1d30a22-9f37-11e5-9a19-5123092296c9.png)

If you want to bid on players and snipe, then leave that checkbox unchecked.

**Comment by hunterjm** [comment] 2015-12-11 04:26
Regarding the `KeyError: 'Desc'`, clean out your tradepile before bidding.  Closing this as it's a duplicate of https://github.com/hunterjm/futgui/issues/25

**Closed as completed by hunterjm** 2015-12-11 04:26 UTC
Labels: duplicate
